# Interface for RU (Fronthaul - gNB to Radio Unit/USRP)
apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata: # kpt-merge: oai-ran/ru
  name: ru
  namespace: oai-ran
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.gnb
    specializer.nephio.org/namespace: oai-ran
    internal.kpt.dev/upstream-identifier: 'req.nephio.org|Interface|oai-ran|ru'
  labels:
    nephio.org/interface: ru
    nephio.org/nf: gnb
    nephio.org/deployment-type: monolithic
spec:
  networkInstance:
    name: vpc-fronthaul
  cniType: macvlan
status:
  ipClaimStatus:
  - prefix: 10.2.6.0/24
    gateway: ""
