# NetworkInstance for N2 control plane
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata: # kpt-merge: oai-ran/vpc-control
  name: vpc-control
  namespace: oai-ran
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'infra.nephio.org|NetworkInstance|oai-ran|vpc-control'
  labels:
    nephio.org/network: control
    nephio.org/nf-type: gnb
spec:
  name: vpc-control
  interfaces:
  - kind: bridgedomain
  - kind: interface
    selector:
      matchLabels:
        nephio.org/interface: n2
  pools:
  - name: n2-ipv4-pool
    prefixLength: 24
