# NetworkInstance for N3 user plane
apiVersion: infra.nephio.org/v1alpha1
kind: NetworkInstance
metadata: # kpt-merge: oai-ran/vpc-userplane
  name: vpc-userplane
  namespace: oai-ran
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'infra.nephio.org|NetworkInstance|oai-ran|vpc-userplane'
  labels:
    nephio.org/network: userplane
    nephio.org/nf-type: gnb
spec:
  name: vpc-userplane
  interfaces:
  - kind: bridgedomain
  - kind: interface
    selector:
      matchLabels:
        nephio.org/interface: n3
  pools:
  - name: n3-ipv4-pool
    prefixLength: 24
