apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /config-management-system
  name: config-management-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|config-management-system'
---
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: config-management-system/root-reconciler
  name: root-reconciler
  namespace: config-management-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|config-management-system|root-reconciler'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /root-reconciler
  name: root-reconciler
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|root-reconciler'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: root-reconciler
  namespace: config-management-system
---
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: config-management-system/reconciler-manager
  name: reconciler-manager
  namespace: config-management-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|config-management-system|reconciler-manager'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reconciler-manager
  template:
    metadata:
      labels:
        app: reconciler-manager
    spec:
      serviceAccountName: root-reconciler
      containers:
      - name: reconciler-manager
        image: gcr.io/config-management-release/reconciler-manager:v1.17.2
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
