# LimitRange for RAN namespaces
apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: openairinterface/default-limits
  name: default-limits
  namespace: openairinterface
  annotations:
    internal.kpt.dev/upstream-identifier: '|LimitRange|openairinterface|default-limits'
spec:
  limits:
  # Container defaults
  - type: Container
    default:
      cpu: "2" # Default limit if not specified
      memory: "4Gi"
    defaultRequest:
      cpu: "500m" # Default request if not specified
      memory: "1Gi"
    max:
      cpu: "8" # Maximum a single container can request
      memory: "16Gi"
    min:
      cpu: "100m" # Minimum a container must request
      memory: "128Mi"
  # Pod defaults (sum of all containers)
  - type: Pod
    max:
      cpu: "16" # Maximum for entire pod
      memory: "32Gi"
  # PVC defaults
  - type: PersistentVolumeClaim
    max:
      storage: "50Gi" # Maximum PVC size
    min:
      storage: "1Gi" # Minimum PVC size
---
apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: oai-ran-cucp/default-limits
  name: default-limits
  namespace: oai-ran-cucp
  annotations:
    internal.kpt.dev/upstream-identifier: '|LimitRange|oai-ran-cucp|default-limits'
spec:
  limits:
  - type: Container
    default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
---
apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: oai-ran-cuup/default-limits
  name: default-limits
  namespace: oai-ran-cuup
  annotations:
    internal.kpt.dev/upstream-identifier: '|LimitRange|oai-ran-cuup|default-limits'
spec:
  limits:
  - type: Container
    default:
      cpu: "4" # CU-UP needs more for user plane processing
      memory: "8Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    max:
      cpu: "12"
      memory: "24Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
---
apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: oai-ran-du/default-limits
  name: default-limits
  namespace: oai-ran-du
  annotations:
    internal.kpt.dev/upstream-identifier: '|LimitRange|oai-ran-du|default-limits'
spec:
  limits:
  - type: Container
    default:
      cpu: "4" # DU also needs significant resources
      memory: "8Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    max:
      cpu: "16" # DU can use more CPU for PHY processing
      memory: "32Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
---
# LimitRange for Core namespaces
apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: free5gc/default-limits
  name: default-limits
  namespace: free5gc
  annotations:
    internal.kpt.dev/upstream-identifier: '|LimitRange|free5gc|default-limits'
spec:
  limits:
  - type: Container
    default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
  - type: PersistentVolumeClaim
    max:
      storage: "100Gi" # Core needs more storage for databases
    min:
      storage: "1Gi"
---
apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: free5gc-cp/default-limits
  name: default-limits
  namespace: free5gc-cp
  annotations:
    internal.kpt.dev/upstream-identifier: '|LimitRange|free5gc-cp|default-limits'
spec:
  limits:
  - type: Container
    default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
---
apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: free5gc-up/default-limits
  name: default-limits
  namespace: free5gc-up
  annotations:
    internal.kpt.dev/upstream-identifier: '|LimitRange|free5gc-up|default-limits'
spec:
  limits:
  - type: Container
    default:
      cpu: "4" # UPF needs more for packet processing
      memory: "8Gi"
    defaultRequest:
      cpu: "1"
      memory: "2Gi"
    max:
      cpu: "16"
      memory: "32Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
