apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /openairinterface
  name: openairinterface
  labels:
    nephio.org/cluster-name: example-cluster # kpt-set: ${cluster-name}
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|openairinterface'
---
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /free5gc
  name: free5gc
  labels:
    nephio.org/cluster-name: example-cluster # kpt-set: ${cluster-name}
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|free5gc'
