apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata: # kpt-merge: config-management-system/root-sync
  name: root-sync
  namespace: config-management-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'configsync.gke.io|RootSync|config-management-system|root-sync'
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/example/repo.git # kpt-set: ${cluster-repo-url}
    branch: main # kpt-set: ${cluster-repo-branch}
    dir: /
    auth: none
    period: 15s
