apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: # kpt-merge: /local-path
  name: local-path # kpt-set: ${storage-class-name}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    internal.kpt.dev/upstream-identifier: 'storage.k8s.io|StorageClass|default|local-path'
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: # kpt-merge: /local-path-retain
  name: local-path-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    internal.kpt.dev/upstream-identifier: 'storage.k8s.io|StorageClass|default|local-path-retain'
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: false
