apiVersion: nephio.org/v1alpha1
kind: NetworkIntent
metadata: # kpt-merge: /control-plane-intent
  name: control-plane-intent
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'nephio.org|NetworkIntent|default|control-plane-intent'
spec:
  networkName: control-plane
  interfaceType: macvlan # kpt-set: ${cni-type}
  macvlanConfig:
    mode: bridge # kpt-set: ${macvlan-mode}
    master: eth0 # kpt-set: ${interface-name}
  ipAllocation:
    type: whereabouts
    ranges:
    - subnet: 192.168.10.0/24 # kpt-set: ${control-plane-range}
      gateway: 192.168.10.1 # kpt-set: ${control-plane-gateway}
      rangeStart: 192.168.10.10
      rangeEnd: 192.168.10.250
  vlanConfig:
    vlanId: 0 # kpt-set: ${control-plane-vlan}
  mtu: 1500 # kpt-set: ${mtu}
  targetNamespace: default # kpt-set: ${target-namespace}
---
apiVersion: nephio.org/v1alpha1
kind: NetworkIntent
metadata: # kpt-merge: /user-plane-intent
  name: user-plane-intent
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'nephio.org|NetworkIntent|default|user-plane-intent'
spec:
  networkName: user-plane
  interfaceType: macvlan # kpt-set: ${cni-type}
  macvlanConfig:
    mode: bridge # kpt-set: ${macvlan-mode}
    master: eth0 # kpt-set: ${interface-name}
  ipAllocation:
    type: whereabouts
    ranges:
    - subnet: 192.168.20.0/24 # kpt-set: ${user-plane-range}
      gateway: 192.168.20.1 # kpt-set: ${user-plane-gateway}
      rangeStart: 192.168.20.10
      rangeEnd: 192.168.20.250
  vlanConfig:
    vlanId: 0 # kpt-set: ${user-plane-vlan}
  mtu: 1500 # kpt-set: ${mtu}
  targetNamespace: default # kpt-set: ${target-namespace}
