# Resource quotas for network function namespaces
# NOTE: LimitRange resources are already defined in cluster-baseline
# This file only contains ResourceQuotas to avoid duplicates

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ran-quota
  namespace: openairinterface
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "30"
    limits.memory: 60Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: core-quota
  namespace: free5gc
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "30"
    limits.memory: 60Gi
    persistentvolumeclaims: "10"
