apiVersion: v1
kind: ResourceQuota
metadata: # kpt-merge: openairinterface/ran-quota
  name: ran-quota
  namespace: openairinterface
  annotations:
    internal.kpt.dev/upstream-identifier: '|ResourceQuota|openairinterface|ran-quota'
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "30"
    limits.memory: 60Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata: # kpt-merge: free5gc/core-quota
  name: core-quota
  namespace: free5gc
  annotations:
    internal.kpt.dev/upstream-identifier: '|ResourceQuota|free5gc|core-quota'
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "30"
    limits.memory: 60Gi
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: openairinterface/default-limits
  name: default-limits
  namespace: openairinterface
  annotations:
    internal.kpt.dev/upstream-identifier: '|LimitRange|openairinterface|default-limits'
spec:
  limits:
  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: "500m"
      memory: 1Gi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata: # kpt-merge: free5gc/default-limits
  name: default-limits
  namespace: free5gc
  annotations:
    internal.kpt.dev/upstream-identifier: '|LimitRange|free5gc|default-limits'
spec:
  limits:
  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: "500m"
      memory: 1Gi
    type: Container
