apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multus
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ['*']
    verbs: ['*']
  - apiGroups: [""]
    resources: [pods, pods/status]
    verbs: [get, update]
  - apiGroups: ["", events.k8s.io]
    resources: [events]
    verbs: [create, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus
subjects:
- kind: ServiceAccount
  name: multus
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
    spec:
      hostNetwork: true
      serviceAccountName: multus
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: kube-multus
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.2 # kpt-set: ${multus-image}
        command: ["/thin_entrypoint"]
        args:
        - "--multus-conf-file=auto"
        - "--multus-autoconfig-dir=/host/etc/cni/net.d"
        - "--cni-conf-dir=/host/etc/cni/net.d"
        - "--multus-kubeconfig-file-host=/etc/cni/net.d/multus.d/multus.kubeconfig"
        - "--namespace-isolation=true"
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "NET_ADMIN"]
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
      initContainers:
      - name: install-cni-plugins
        image: ghcr.io/k8snetworkplumbingwg/plugins:v1.6.2 # kpt-set: ${cni-plugins-image}
        command:
          - "sh"
          - "-c"
          - |
            cp /opt/cni/bin/macvlan /host/opt/cni/bin/macvlan
            cp /opt/cni/bin/ipvlan /host/opt/cni/bin/ipvlan
            cp /opt/cni/bin/vlan /host/opt/cni/bin/vlan
            cp /opt/cni/bin/bridge /host/opt/cni/bin/bridge
            cp /opt/cni/bin/host-device /host/opt/cni/bin/host-device
            cp /opt/cni/bin/tuning /host/opt/cni/bin/tuning
            chmod +x /host/opt/cni/bin/macvlan
            chmod +x /host/opt/cni/bin/ipvlan
            chmod +x /host/opt/cni/bin/vlan
            chmod +x /host/opt/cni/bin/bridge
            chmod +x /host/opt/cni/bin/host-device
            chmod +x /host/opt/cni/bin/tuning
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
