apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multus
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ['*']
    verbs: ['*']
  - apiGroups: [""]
    resources: [pods, pods/status]
    verbs: [get, update]
  - apiGroups: ["", events.k8s.io]
    resources: [events]
    verbs: [create, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus
subjects:
- kind: ServiceAccount
  name: multus
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
    spec:
      hostNetwork: true
      serviceAccountName: multus
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: kube-multus
        image: ghcr.io/k8snetworkplumbingwg/multus-cni:v4.0.2 # kpt-set: ${multus-image}
        command: ["/thin_entrypoint"]
        args:
        - "--multus-conf-file=auto"
        - "--multus-autoconfig-dir=/host/etc/cni/net.d"
        - "--cni-conf-dir=/host/etc/cni/net.d"
        - "--multus-kubeconfig-file-host=/etc/cni/net.d/multus.d/multus.kubeconfig"
        - "--namespace-isolation=true"
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "NET_ADMIN"]
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
      initContainers:
      - name: install-cni-plugins
        image: ghcr.io/k8snetworkplumbingwg/plugins:v1.6.2
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "=== Searching for CNI plugins in image ==="
            find / -name macvlan -type f 2>/dev/null || true
            echo "=== Listing common CNI paths ==="
            ls -la /opt/cni/bin/ 2>/dev/null || true
            ls -la /plugins/ 2>/dev/null || true
            ls -la / 2>/dev/null | grep -E "macvlan|ipvlan|bridge|tuning" || true
            echo "=== Checking host /opt/cni/bin ==="
            ls -la /host/opt/cni/bin/ 2>/dev/null || true
            echo "=== Attempting copies from all known paths ==="
            for plugin in macvlan ipvlan bridge tuning; do
              SRC=$(find / -name "$plugin" -type f ! -path "/host/*" ! -path "/proc/*" ! -path "/sys/*" 2>/dev/null | head -1)
              if [ -n "$SRC" ]; then
                echo "Found $plugin at $SRC, copying..."
                cp "$SRC" /host/opt/cni/bin/
                chmod +x /host/opt/cni/bin/$plugin
              elif [ -f /host/opt/cni/bin/$plugin ]; then
                echo "$plugin already exists on host, skipping"
              else
                echo "WARNING: $plugin not found in image or on host"
              fi
            done
            echo "=== Final state of /host/opt/cni/bin ==="
            ls -la /host/opt/cni/bin/ | grep -E "macvlan|ipvlan|bridge|tuning" || true
            echo "Done"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
