# Metrics Server for resource metrics (CPU/memory)
# Required for kubectl top and HPA
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: kube-system/metrics-server
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|kube-system|metrics-server'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /system:aggregated-metrics-reader
  name: system:aggregated-metrics-reader
  labels:
    k8s-app: metrics-server
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|system:aggregated-metrics-reader'
rules:
- apiGroups: [metrics.k8s.io]
  resources: [pods, nodes]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /system:metrics-server
  name: system:metrics-server
  labels:
    k8s-app: metrics-server
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|system:metrics-server'
rules:
- apiGroups: [""]
  resources: [nodes/metrics]
  verbs: [get]
- apiGroups: [""]
  resources: [pods, nodes]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /metrics-server:system:auth-delegator
  name: metrics-server:system:auth-delegator
  labels:
    k8s-app: metrics-server
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|metrics-server:system:auth-delegator'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: # kpt-merge: /system:metrics-server
  name: system:metrics-server
  labels:
    k8s-app: metrics-server
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRoleBinding|default|system:metrics-server'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:metrics-server
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata: # kpt-merge: kube-system/metrics-server
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|kube-system|metrics-server'
spec:
  selector:
    k8s-app: metrics-server
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
---
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: kube-system/metrics-server
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|kube-system|metrics-server'
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      containers:
      - name: metrics-server
        image: registry.k8s.io/metrics-server/metrics-server:v0.7.0
        imagePullPolicy: IfNotPresent
        args:
        - --cert-dir=/tmp
        - --secure-port=4443
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
        ports:
        - name: https
          containerPort: 4443
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
      volumes:
      - name: tmp-dir
        emptyDir: {}
      priorityClassName: system-cluster-critical
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata: # kpt-merge: /v1beta1.metrics.k8s.io
  name: v1beta1.metrics.k8s.io
  labels:
    k8s-app: metrics-server
  annotations:
    internal.kpt.dev/upstream-identifier: 'apiregistration.k8s.io|APIService|default|v1beta1.metrics.k8s.io'
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
