# NFDeployment for CUCP — required by interface-fn and nad-fn
# This is a local-config resource; it won't be deployed to the cluster
apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: oai-ran/cucp
  name: cucp
  namespace: oai-ran
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|oai-ran|cucp'
spec:
  provider: cucp.openairinterface.org
  interfaces:
  - name: n2
    networkInstance:
      name: vpc-ran
  - name: e1
    networkInstance:
      name: vpc-cu-e1
  - name: f1c
    networkInstance:
      name: vpc-cudu-f1
